<a href="https://colab.research.google.com/github/dlvvkfl88/CS-Knowldege/blob/main/O'REILLY_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_3_4(127p_~.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy 기본 : 배열과 벡터 연산

In [ ]:
import numpy as np

my_arr = np.arange(100000)

my_list = list(range(100000))

4.1 numpy ndarray 다차원 배열 객체

In [ ]:
import numpy as np

In [ ]:
data = np.random.randn(2,3)

In [ ]:
data

array([[ 1.2243825 , -0.30173246,  1.32048469],
       [ 0.16269033,  0.97192992, -0.52092383]])

In [ ]:
data*10

array([[12.24382496, -3.01732462, 13.20484692],
       [ 1.62690332,  9.71929923, -5.20923833]])

In [ ]:
data.shape

data.dtype

dtype('float64')

## ndarray 생성하기

In [ ]:
data1 = [6,7.5,8,0,1]
arr1 =np.array(data1)

arr1



array([6. , 7.5, 8. , 0. , 1. ])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr1 = np.array([1,2,3],dtype=np.float64)

arr2 = np.array([1,2,3], dtype=np.int32)

arr1.dtype


dtype('float64')

### 4.1.3 numpy 배열의 산술 연산

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [ ]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## 4.1.4 색인과 슬라이싱 기초

In [ ]:
arr= np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

5

In [ ]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr[5:8] =12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [ ]:
arr_slice[1] = 12345

arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [ ]:
arr_slice[:] = 64

In [ ]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr2d[2]
arr2d[0][2]

3

## 4.1.5 불리언 값으로 선택하기

In [1]:
import numpy as np

In [2]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

data = np.random.randn(7,4)

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [3]:
data[names == 'Bob']

array([[-1.61041038, -0.75324899,  0.82882471, -1.98724029],
       [-0.04106115, -0.79370629, -1.36920619, -0.15312645]])

In [4]:
data[names == 'Bob',2:]

array([[ 0.82882471, -1.98724029],
       [-1.36920619, -0.15312645]])

In [5]:
data[~(names =='Bob')]

array([[ 2.75693334, -0.19052228, -1.18642304,  0.93953283],
       [-0.78520195,  0.40555314, -0.09783507,  0.5508764 ],
       [ 0.86515122, -0.16156046, -0.44453572,  0.47809333],
       [ 0.61606301,  1.34255557,  1.80698763, -0.96561297],
       [-0.49599918, -0.45035314,  0.89459144,  0.58007837]])

4.16 팬시색인

-- 팬시색인은 정수 배열을 사용한 색인을 설명하귀 위해 Numpy에서 차용한 단어다. 8x4크기 배열이 있다고 가정

In [6]:
arr = np.empty(((8,4)))

In [8]:
for i in range(8):
    arr[i] = i

In [11]:
np.dot(arr.T,arr) # 행렬 곱 내적

array([[140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.]])

## 4.2 유니버셜 함수 배열의 각 원소 빠르게 처리하는 함수

In [13]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x = np.random.randn(8)

y = np.random.randn(8)

In [15]:
np.maximum(x,y)

array([ 0.00745987,  0.13831609,  0.67471709,  0.77197267, -1.09431545,
        0.79798908,  0.05002114, -0.10427837])

### 4.3 배열을 이용한 배열지향 프로그래밍

In [16]:
points = np.arange(-5,5,0.01)# -5  4.99까지 0.01씩 증가하는 배열

points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [18]:
xs,ys  = np.meshgrid(points,points)

ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

### 4.3.1 배열연산으로 조건절 표현하기

In [19]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])

yarr = np.array([2.1,2.2,2.3,2.4,2.5])

cond = np.array([True,False,True,True,False])

In [21]:
result = [(x if c else y )
          for x,y,c in zip(xarr,yarr,cond)]

result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [22]:
result = np.where(cond , xarr, yarr)

result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [24]:
arr = np.random.randn(4,4)

arr

array([[ 0.42361954,  1.24385744,  1.0014536 ,  0.454615  ],
       [ 0.65887095,  0.29642308,  0.51319767,  0.807685  ],
       [-0.76036278,  0.93805183, -1.38237168, -1.38159857],
       [ 2.24399994, -0.27343712,  0.30179111,  0.10649122]])

In [25]:
arr>0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True, False, False],
       [ True, False,  True,  True]])

In [26]:
np.where(arr>0,2,-2)

array([[ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [-2,  2, -2, -2],
       [ 2, -2,  2,  2]])

### 4.3.2 수학 메서드와 통계 메서드

In [27]:
arr = np.array([0,1,2,3,4,5,6,7])

arr.cumsum()



array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [28]:
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [30]:
arr.cumprod(axis=1) # 누적곱

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

## 4.3.3 불리언 배열을 위한 메서드

In [33]:
arr = np.random.randn(100)
(arr>0).sum()

50

## 4.3.4 정렬

In [36]:
arr = np.random.randn(6)

arr.sort()

arr

array([-0.98183663, -0.34579443, -0.07518365,  0.08245263,  0.17690387,
        0.79229621])

In [37]:
arr = np.random.randn(5,3)

arr

array([[ 0.18826518,  1.84159821, -0.53833478],
       [ 0.60061989, -0.73350211, -1.67341784],
       [-0.08381154,  1.7082521 , -1.20827692],
       [-2.09670915, -0.97161664,  0.81557203],
       [-1.35019107,  1.26539918, -0.92854601]])

In [39]:
arr.sort(1)

arr

array([[-0.53833478,  0.18826518,  1.84159821],
       [-1.67341784, -0.73350211,  0.60061989],
       [-1.20827692, -0.08381154,  1.7082521 ],
       [-2.09670915, -0.97161664,  0.81557203],
       [-1.35019107, -0.92854601,  1.26539918]])

In [41]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [42]:
sorted(set(names))

['Bob', 'Joe', 'Will']

## 4.5 선형대수

In [44]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])

x,y

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[ 6., 23.],
        [-1.,  7.],
        [ 8.,  9.]]))

In [45]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [46]:
np.dot(x,np.ones(3))

array([ 6., 15.])

In [48]:
x @ np.ones(3)

array([ 6., 15.])