<a href="https://colab.research.google.com/github/dlvvkfl88/CS-Knowldege/blob/main/%EB%8B%A8%EC%88%9C_%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np

## 데이터셋 생성

In [28]:
# [1] 데이터셋 생성

loaded_data = np.loadtxt('./sps.csv', delimiter=',', dtype=np.float32)

x_data = loaded_data[ :, 1:]
t_data = loaded_data[ :, [0]]

# 데이터 차원 및 shape 확인
print("loaded_data.ndim = ", loaded_data.ndim, ", loaded_data.shape = ", loaded_data.shape)
print("x_data.ndim = ", x_data.ndim, ", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim, ", t_data.shape = ", t_data.shape)

loaded_data.ndim =  2 , loaded_data.shape =  (50, 5)
x_data.ndim =  2 , x_data.shape =  (50, 4)
t_data.ndim =  2 , t_data.shape =  (50, 1)


### W,b 초기화 단계

In [29]:
# np.random.seed(0)

# W = np.random.rand(4,1)
# b = np.random.rand(1)

In [30]:
## tensorflow 이용

model = Sequential()
model.add(Dense(1,input_shape=(4,), activation='linear')) # 입력층 + 출력층

In [31]:
print(model.weights )

[<tf.Variable 'dense_1/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[-0.509173 ],
       [-0.3290916],
       [-0.2658205],
       [ 0.5716326]], dtype=float32)>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]


## loss함수 정의 미분방법 정의 // 모델 컴파일

In [32]:
# def loss_func(x,t):
#   y = np.dot(x,W) + b
#   return(np.sum((t-y)**2))/(len(x)) # MSE

In [33]:
# 모델 컴파일 및 summary
model.compile(optimizer=SGD(learning_rate=1e-2), loss='mse')

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 5         
                                                                 
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


## 모델 학습 //model.fit

In [34]:
hist= model.fit(x_data,t_data, epochs=2000)

Epoch 1/2000
2/2 [==============================] - 1s 6ms/step - loss: 50.1411
Epoch 2/2000
2/2 [==============================] - 0s 6ms/step - loss: 22.0479
Epoch 3/2000
2/2 [==============================] - 0s 5ms/step - loss: 10.8879
Epoch 4/2000
2/2 [==============================] - 0s 6ms/step - loss: 4.9628
Epoch 5/2000
2/2 [==============================] - 0s 6ms/step - loss: 2.5886
Epoch 6/2000
2/2 [==============================] - 0s 5ms/step - loss: 1.2515
Epoch 7/2000
2/2 [==============================] - 0s 14ms/step - loss: 0.6329
Epoch 8/2000
2/2 [==============================] - 0s 6ms/step - loss: 0.3260
Epoch 9/2000
2/2 [==============================] - 0s 6ms/step - loss: 0.1716
Epoch 10/2000
2/2 [==============================] - 0s 6ms/step - loss: 0.0887
Epoch 11/2000
2/2 [==============================] - 0s 5ms/step - loss: 0.0473
Epoch 12/2000
2/2 [==============================] - 0s 8ms/step - loss: 0.0256
Epoch 13/2000
2/2 [==========================

In [35]:
print(model.weights) # 학습후 W,b상황

[<tf.Variable 'dense_1/kernel:0' shape=(4, 1) dtype=float32, numpy=
array([[ 1.       ],
       [-1.0000001],
       [ 1.       ],
       [-1.0000001]], dtype=float32)>, <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([3.5526926e-07], dtype=float32)>]


# 예측

In [36]:
ex_data_01 = np.array([[4,4,4,4]])

print("predicted value = ", model.predict(ex_data_01))

1/1 [==============================] - 0s 78ms/step
predicted value =  [[-5.9840505e-07]]


In [38]:
test_data = np.array([[4,4,4,4],
                      [-3,0,9,-1],
                      [-7,-9,-2,8],
                      [1,-2,3,-2],
                      [19,-12,0,-76]])

print(test_data)

print("predicted value = ", model.predict(test_data))

[[  4   4   4   4]
 [ -3   0   9  -1]
 [ -7  -9  -2   8]
 [  1  -2   3  -2]
 [ 19 -12   0 -76]]
1/1 [==============================] - 0s 23ms/step
predicted value =  [[-5.9840505e-07]
 [ 7.0000005e+00]
 [-7.9999995e+00]
 [ 8.0000000e+00]
 [ 1.0700001e+02]]
